repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: detect-aws-credentials
        args: [ --allow-missing-credentials ] # OK if user has no credentials
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: check-xml
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.1
    hooks:
      - id: shellcheck
