FROM jenkins/jenkins:lts
LABEL maintainer="mvartanian@ncbi.nlm.nih.gov"

# if we want to install via apt
USER root
RUN apt-get update && apt-get install -y
# drop back to the regular jenkins user - good practice
USER jenkins
RUN MKDIR -p $JENKINS_HOME/jobs/ncbi
COPY jobs/ncbi-drs/config.xml $JENKINS_HOME/jobs/ncbi/
